export const seedCategories = [
  {
    id: "2a283e6f-ba0d-4687-b581-c64cfcb0b4d4",
    name: "PLASTIC & HOUSEHOLD ITEMS",
    description: "Durable household items",
    icon: "box",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "3d2d0267-e431-4ce5-b113-85d07a742085",
    name: "FANCY / GIFT ITEMS",
    description: "Lifestyle / decor",
    icon: "gift",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "3df6b5cd-5d7a-48b1-87eb-97f21d10dccf",
    name: "PERSONAL CARE",
    description: "Self-care & hygiene",
    icon: "heart",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "41aaff61-6e54-4768-824d-52865293094c",
    name: "SNACKS & SWEETS",
    description: "Impulse / treat spending",
    icon: "cookie",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "4d6f32d3-57cc-417e-a4e6-0cbac1f459ca",
    name: "PACKAGED FOOD",
    description: "Instant / processed food",
    icon: "package",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "506954d0-d5c1-495b-9652-1a912d0d3813",
    name: "DAIRY",
    description: "Daily nutrition items",
    icon: "milk",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "6500e86b-80fb-4670-8fae-3dcd78738dd0",
    name: "DINING OUT",
    description: "Restaurant & delivery food",
    icon: "chef-hat",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "6df474da-de00-4d29-ac8d-a789a6588fdb",
    name: "CHICKEN WITH SKIN",
    description: "Chicken",
    icon: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "7c46fdbf-9df0-4bf8-9e0c-b2ee9722d256",
    name: "MEDICAL / HEALTH",
    description: "Medicines & healthcare",
    icon: "activity",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "857bdec9-abff-4e88-8058-8ca7e32d5547",
    name: "LIFESTYLE / ACTIVITIES",
    description:
      "Spending related to personal activities, fitness, hobbies, leisure, and lifestyle choices (non-essential items).",
    icon: "film",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "9d06c274-e267-40c0-88e6-cb73912b7c7e",
    name: "GROCERY (STAPLES)",
    description:
      "Rice, Wheat / Atta, Toor Dal, Moong Dal, Cooking Oil, Sugar, Salt, Basic Spices",
    icon: "shopping-basket",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "a2548696-fe8f-467c-a9f4-b31f92bc8ccd",
    name: "CLOTHING / DRESS",
    description: "Apparel & fashion",
    icon: "shirt",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "a4c09808-220d-4abc-bfb6-86f72a05fb1e",
    name: "EDUCATION",
    description:
      "Expenses related to education, learning, stationery, books, and study materials.",
    icon: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "a9c0bbdf-bb6f-4b5e-b559-b4df41a6d347",
    name: "UTENSILS / METAL ITEMS",
    description: "Long-term household assets",
    icon: "utensils",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ba65ae22-235e-49a4-bbf0-5ec349710dcf",
    name: "VEGETABLES",
    description: "Fresh, perishable, health-driven",
    icon: "leaf",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "bac1529f-e524-4604-a647-d8dd89e00ae3",
    name: "FUEL / TRANSPORT",
    description: "Mobility & travel",
    icon: "car",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "e5dcb941-c9db-4198-8ad5-daf0ad716827",
    name: "HOUSEHOLD SUPPLIES",
    description: "Home maintenance & cleaning",
    icon: "spray-can",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ef3253c2-a8ba-4690-8b92-5d6f4f9df4ac",
    name: "FRUITS",
    description: "Fresh, optional, lifestyle-dependent",
    icon: "apple",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "fa2003bb-9aaa-4b43-a8d4-56691f0b0de1",
    name: "MISCELLANEOUS",
    description: "Catch-all expenses (use sparingly)",
    icon: "help-circle",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "fde0a405-fbe3-408e-9bc8-d9014830337b",
    name: "BEVERAGES",
    description: "Consumables, habit-based",
    icon: "coffee",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
